version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - api

  api:
  build: ./api
  ports:
    - "3000:3000"
  environment:
    MONGODB_HOST: localhost  # Nombre del servicio de MongoDB
    PORT_DATABASE: 27017
    NAME_DATABASE: mydatabase
  depends_on:
    - db

  db:
    image: mongo:5.0  # Usar la imagen oficial de MongoDB
    container_name: db_container
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db  # Persistencia de datos

volumes:
  mongo_data:

networks:
  backend:
    driver: bridge