version: '3.8'

services:
  frontend:
    build: 
      context: './frontend'
      dockerfile: dockerfile
    ports:
      - "80:80"
    networks:
      - frontend
    depends_on:
      - api

  api:
    build: 
      context: './api'  # Ruta al Dockerfile de la API
      dockerfile: dockerfile
    ports:
      - "3000:3000"  # Mapeo de puertos (host:contenedor)
    environment:
      - NODE_ENV=production
    env_file: ./api/.env
    networks:
      - backend
    depends_on:
      - db  # Depende del servicio de MongoDB

  db:
    image: mongo:5.0
    container_name: db_container
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: mydatabase

volumes:
  mongo_data:

networks:
  backend:
    driver: bridge